// <auto-generated />
using System;
using ClaudeCereal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaudeCereal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601091003_AddAuditCorrelationId")]
    partial class AddAuditCorrelationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ClaudeCereal.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EntityId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ClaudeCereal.Models.Cereal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Carbo")
                        .HasColumnType("REAL");

                    b.Property<double?>("Cups")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Fat")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Fiber")
                        .HasColumnType("REAL");

                    b.Property<string>("Mfr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Potass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Protein")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("Shelf")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sodium")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sugars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Vitamins")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.ToTable("Cereals");
                });

            modelBuilder.Entity("ClaudeCereal.Models.AuditLog", b =>
                {
                    b.OwnsMany("ClaudeCereal.Models.AuditFieldChange", "Changes", b1 =>
                        {
                            b1.Property<int>("AuditLogId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Field")
                                .IsRequired();

                            b1.Property<string>("NewValue");

                            b1.Property<string>("OldValue");

                            b1.HasKey("AuditLogId", "__synthesizedOrdinal");

                            b1.ToTable("AuditLogs");

                            b1
                                .ToJson("Changes")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogId");
                        });

                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
